# Generated by Django 4.0.4 on 2022-05-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptp', '0003_alter_item_color_alter_item_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='item',
            name='contributor',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
